cloud/endagaweb/urls.py
"""Our endpoints.

Copyright (c) 2016-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
"""

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin, auth
import django.contrib.auth.views

import endagaweb.views

import endagaweb.stats_app

import rest_framework.authtoken.views


urlpatterns = [
    # API v1.
    url(r'^api-token-auth/',
        rest_framework.authtoken.views.obtain_auth_token),
    url(r'^api/v1/register/(.*)/(.*)/',
        endagaweb.views.api.Register.as_view()),
    url(r'^api/v1/register/', endagaweb.views.api.Register.as_view()),
    url(r'^api/v1/fetch/(.*)/', endagaweb.views.api.GetNumber.as_view()),
    url(r'^api/v1/fetch/', endagaweb.views.api.GetNumber.as_view()),
    url(r'^api/v1/send/', endagaweb.views.api.SendSMS.as_view()),
    url(r'^api/v1/inbound/', endagaweb.views.api.InboundSMS.as_view()),
    url(r'^api/v1/receipt/',
        endagaweb.views.api.InboundReceipt.as_view()),
    url(r'^api/v1/checkin', endagaweb.views.api.Checkin.as_view()),
    url(r'^api/v1/bts/sslconf', endagaweb.views.api.SSLConfig.as_view()),
    url(r'^api/v1/bts/register',
        endagaweb.views.api.BTSRegistration.as_view()),
    url(r'^api/v1/bts/logfile',
        endagaweb.views.api.BTSLogfile.as_view()),
    # API v2.
    # /numbers/<number> -- POST to start the number-deactivation process.
    url(r'^api/v2/numbers/(?P<msisdn>[0-9]+)$',
        endagaweb.views.api_v2.Number.as_view(), name='number'),
    # /towers/<uuid> -- DELETE to start the bts deregistration process.
    url(r'^api/v2/towers/(?P<tower_uuid>[A-Za-z0-9-]+)$',
        endagaweb.views.api_v2.Tower.as_view(), name='apiv2_tower'),
    # /subscribers/<imsi> -- DELETE to start the sub-deactivation process.
    url(r'^api/v2/subscribers/(?P<imsi>[^/]+)$',
        endagaweb.views.api_v2.Subscriber.as_view(), name='v2_subscribers'),

    # Routes for the new stats API, not to be confused with /stats (below).
    # Passes the infrastructure level in the URL (global, network, etc) and the
    # level id as a query param.
    url(r'^api/v1/stats/(.*)',
        endagaweb.stats_app.views.StatsAPIView.as_view()),

    # the internal API.
    url(r'^internal/api/v1/number/',
        endagaweb.views.internalapi.NumberLookup.as_view()),
    url(r'^internal/api/v1/uuid/',
        endagaweb.views.internalapi.UUIDLookup.as_view()),
    url(r'^internal/api/v1/auth/',
        endagaweb.views.internalapi.NumberAuth.as_view()),
    url(r'^internal/api/v1/voice/',
        endagaweb.views.internalapi.BillVoice.as_view()),

    # Our homepage.
    url(r'^$', endagaweb.views.static.LandingIndexView.as_view()),

    # ELB testing endpoint
    url(r'^django-status', endagaweb.views.static.TestView.as_view()),

    # Notification emails and phone nnumbers
    url(r'^account/notify_emails/update', endagaweb.views.user.update_notify_emails),
    url(r'^account/notify_numbers/update', endagaweb.views.user.update_notify_numbers),

    # Auth.
    url(r'^login/$', endagaweb.views.user.loginview, name='endagaweb-login'),
    url(r'^auth/', endagaweb.views.user.auth_and_login),
    url(r'^account/password/change', endagaweb.views.user.change_password),
    url(r'^account/update', endagaweb.views.user.update_contact),
    url(r'^account/', endagaweb.views.dashboard.dashboard_view),
    url(r'^logout/$', django.contrib.auth.views.logout, {'next_page': '/'}),

    # Dashboard.
    url(r'^dashboard/card', endagaweb.views.dashboard.addcard),
    url(r'^addmoney/', endagaweb.views.dashboard.addmoney),
    url(r'^dashboard/billing', endagaweb.views.dashboard.billing_view),
    url(r'^dashboard/profile', endagaweb.views.dashboard.profile_view),
    # Tower views in the dashboard.
    # /towers -- GET a list of towers or POST here to add one
    # /towers/<uuid> -- GET details on one tower
    # /towers/<uuid>/monitor -- GET related TimeseriesStats
    # /towers/<uuid>/edit -- GET details on one tower or POST to change them
    # /towers/<uuid>/deregister -- GET a UI for deregistering
    # /towers/<uuid>/tower_events -- GET related tower events
    url(r'^dashboard/towers$',
        endagaweb.views.towers.TowerList.as_view(),
        name='tower-list'),
    url(r'^dashboard/towers/(?P<uuid>[A-Za-z0-9-]+)$',
        endagaweb.views.towers.TowerInfo.as_view(),
        name='tower-info'),
    url(r'^dashboard/towers/(?P<uuid>[A-Za-z0-9-]+)/monitor$',
        endagaweb.views.towers.TowerMonitor.as_view(),
        name='tower-monitor'),
    url(r'^dashboard/towers/(?P<uuid>[A-Za-z0-9-]+)/edit$',
        endagaweb.views.towers.TowerEdit.as_view(),
        name='tower-edit'),
    url(r'^dashboard/towers/(?P<uuid>[A-Za-z0-9-]+)/deregister$',
        endagaweb.views.towers.TowerDeregister.as_view(),
        name='tower-deregister'),
    url(r'^dashboard/towers/(?P<uuid>[A-Za-z0-9-]+)/tower_events$',
        endagaweb.views.towers.TowerEvents.as_view(),
        name='tower-events'),
    # Subscriber views in the dashboard.
    url(r'^dashboard/subscribers$',
        endagaweb.views.dashboard.subscriber_list_view),
    url(r'^dashboard/subscribers/(?P<imsi>[^/]+)$',
        endagaweb.views.dashboard.SubscriberInfo.as_view(),
        name='subscriber-info'),
    url(r'^dashboard/subscribers/(?P<imsi>[^/]+)/activity$',
        endagaweb.views.dashboard.SubscriberActivity.as_view(),
        name='subscriber-activity'),
    url(r'^dashboard/subscribers/(?P<imsi>[^/]+)/send-sms$',
        endagaweb.views.dashboard.SubscriberSendSMS.as_view(),
        name='subscriber-send-sms'),
    url(r'^dashboard/subscribers/(?P<imsi>[^/]+)/adjust-credit$',
        endagaweb.views.dashboard.SubscriberAdjustCredit.as_view(),
        name='subscriber-adjust-credit'),
    url(r'^dashboard/subscribers/(?P<imsi>[^/]+)/edit$',
        endagaweb.views.dashboard.SubscriberEdit.as_view(),
        name='subscriber-edit'),
    # Network views in the dashboard.
    # /network -- GET basic network info
    # /network/prices -- GET pricing data for the network or POST to change it
    # /network/edit -- GET details on the network or POST to change them
    url(r'^dashboard/network$',
        endagaweb.views.network.NetworkInfo.as_view(),
        name='network-info'),
    url(r'^dashboard/network/prices$',
        endagaweb.views.network.NetworkPrices.as_view(),
        name='network-prices'),
    url(r'^dashboard/network/inactive-subscribers$',
        endagaweb.views.network.NetworkInactiveSubscribers.as_view(),
        name='network-inactive-subscribers'),
    url(r'^dashboard/network/edit$',
        endagaweb.views.network.NetworkEdit.as_view(),
        name='network-edit'),
    url(r'^dashboard/network/select/(?P<network_id>[0-9]+)$',
        endagaweb.views.network.NetworkSelectView.as_view()),
    # The activity table.
    url(r'^dashboard/activity',
        endagaweb.views.dashboard.ActivityView.as_view(),
        name='network-activity'),

    # Raise a server error on-demand to test the 500 template.
    url(r'^insta-five-hundred$',
        endagaweb.views.static.InstaFiveHundred.as_view()),

    # OAuth login TODO(omar): setup OAuth provider
    url(r'^staff-login/', endagaweb.views.user.staff_login_view),
    url(r'^accounts/', include('allauth.urls')),
]


if 'django.contrib.admin' in settings.INSTALLED_APPS:
    # Only show the all-numbers table, the all-towers table and the margin
    # analysis page in staff-mode.
    urlpatterns += [
        url(r'^dashboard/staff/all-numbers$',
            endagaweb.views.staff.Numbers.as_view()),
        url(r'^dashboard/staff/all-towers$',
            endagaweb.views.staff.Towers.as_view()),
        url(r'^dashboard/staff/margin-analysis$',
            endagaweb.views.staff.MarginAnalysis.as_view(),
            name='margin-analysis'),
        url(r'^dashboard/staff/tower-monitoring$',
            endagaweb.views.staff.TowerMonitoring.as_view(),
            name='tower-monitoring'),
        url(r'^dashboard/staff/tower-monitoring\?tower=(?P<tower>[0-9-]+)$',
            endagaweb.views.staff.TowerMonitoring.as_view(),
            name='tower-monitoring'),
        url(r'^dashboard/staff/network-earnings$',
            endagaweb.views.staff.NetworkEarnings.as_view(),
            name='network-earnings'),
    ]


urlpatterns += [
    # The dashboard 'home'.
    url(r'^dashboard', endagaweb.views.dashboard.dashboard_view),

    # Old stats.
    url(r'^stats/numbers', endagaweb.views.stats.numbers),
    url(r'^stats/totals', endagaweb.views.stats.totals),

    # Debug.
    url(r'^debug', endagaweb.views.debug.debug_view),
]


# Only use django admin outside of prod.
if 'django.contrib.admin' in settings.INSTALLED_APPS:
    # Register any apps that have admin functionality and add new URLs.
    admin.autodiscover()
    urlpatterns += [
        url(r'^django-admin/', include(admin.site.urls)),
    ]


# We only install the loginas app in the staff version of the site and we hide
# the ghosting routes in other versions.
if 'loginas' in settings.INSTALLED_APPS:
    urlpatterns += url(r'^django-admin/', include('loginas.urls')),

if 'DatabaseStorage' in settings.DEFAULT_FILE_STORAGE:
    urlpatterns += [
        url(r'^file/(?P<fname>.+)$',
            endagaweb.views.file_upload.file_view, name='file-upload')
    ]

cloud/urls.py
"""
Copyright (c) 2016-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
"""
from django.conf.urls import include, url

urlpatterns = [
    url(r'', include('endagaweb.urls')),
    url(r'^sason/', include('sason.urls'))
]

cloud/endagaweb/views/api_v2.py
"""API V2 views.

/numbers/<number> -- POST to deactivate a number

Copyright (c) 2016-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant 
of patent rights can be found in the PATENTS file in the same directory.
"""

import datetime
import json
import uuid

from django.conf import settings
import itsdangerous
import pytz
from rest_framework import status
from rest_framework.views import APIView
from rest_framework import authentication
from rest_framework import permissions
from rest_framework.response import Response

from endagaweb.ic_providers.nexmo import NexmoProvider
from endagaweb.util.api import get_network_from_user
from endagaweb import models
from endagaweb import tasks

class Number(APIView):
    """Handles /api/v2/numbers and /api/v2/numbers/<number>."""

    # Setup DRF permissions and auth.  This endpoint should only be accessed
    # via token auth, but for DRF to work properly you must also enable
    # session auth.

    # CURRENTLY BROKEN FOR NON-NEXMO NUMBERS -Kurtis
    # https://github.com/endaga/endaga-web/issues/406
    permission_classes = (permissions.IsAuthenticated,)
    authentication_classes = (authentication.SessionAuthentication,
                              authentication.TokenAuthentication)

    def post(self, request, msisdn):
        network = get_network_from_user(request.user)
        number = models.Number.objects.get(number=msisdn)
        if (number.network and number.network != network
                and not request.user.is_staff):
            return Response("User is not associated with that Number %s %s." %(number.network.pk, network.pk),
                            status=status.HTTP_403_FORBIDDEN)
        # Must post a valid 'state'.
        valid_states = ('available', 'released')
        if request.POST.get('state', None) not in valid_states:
            return Response("Must post a valid state.",
                            status=status.HTTP_400_BAD_REQUEST)
        # This is a valid request, begin processing.  First check if this is a
        # number-deactivation request.
        if (number.state == 'inuse' and
                request.POST.get('state') == 'available'):
            # Refuse to deactivate a subscriber's last number.
            if (len(models.Number.objects.filter(subscriber=number.subscriber))
                    <= 1):
                message = ("Cannot deactivate a subscriber's last number."
                           "  Instead, delete the subscriber.")
                return Response(message, status=status.HTTP_400_BAD_REQUEST)
            # If it's not the subscriber's only number, send an async post to
            # the BTS to deactivate the number.  Sign the request using JWT.
            bts = number.subscriber.bts
            url = '%s/config/deactivate_number' % bts.inbound_url
            data = {
                'number': msisdn,
                # Add a UUID as a nonce for the message.
                'msgid': str(uuid.uuid4()),
            }
            serializer = itsdangerous.JSONWebSignatureSerializer(bts.secret)
            signed_data = {
                'jwt': serializer.dumps(data),
            }
            tasks.async_post.delay(url, signed_data)
            # Create a 'deactivate_number' UsageEvent.
            now = datetime.datetime.now(pytz.utc)
            reason = 'deactivated phone number: %s' % number.number
            event = models.UsageEvent.objects.create(
                subscriber=number.subscriber, date=now, bts=bts,
                kind='deactivate_number', to_number=number.number,
                reason=reason, oldamt=number.subscriber.balance,
                newamt=number.subscriber.balance, change=0)
            event.save()
            # Diassociate the Number from its former Subscriber and Network.
            number.subscriber = None
            number.network = None
            number.state = request.POST.get('state')
            number.save()
            return Response("")

        # Check if this is a number-release request.
        if request.POST.get('state') == 'released':
            # User must be staff to do this.
            if not request.user.is_staff:
                return Response("", status=status.HTTP_404_NOT_FOUND)
            # The number must not be 'inuse.'
            if number.state == 'inuse':
                return Response("", status=status.HTTP_400_BAD_REQUEST)
            # The number cannot be associated with a Sub.
            if number.subscriber:
                return Response("", status=status.HTTP_400_BAD_REQUEST)
            # Validation passes, release (cancel) the number.
            nexmo_provider = NexmoProvider(
                settings.ENDAGA['NEXMO_ACCT_SID'],
                settings.ENDAGA['NEXMO_AUTH_TOKEN'],
                settings.ENDAGA['NEXMO_INBOUND_SMS_URL'],
                None,
                settings.ENDAGA['NEXMO_INBOUND_VOICE_HOST'],
                country=number.country_id)
            if nexmo_provider.cancel_number(number.number):
                # Success, delete the number.
                number.delete()
                return Response("", status=status.HTTP_200_OK)
            else:
                print 'deleting number %s failed' % number.number
                return Response(
                    "", status=status.HTTP_500_INTERNAL_SERVER_ERROR)

        # Invalid request.
        return Response("", status=status.HTTP_400_BAD_REQUEST)


class Subscriber(APIView):
    """Handles /api/v2/subscribers and /api/v2/subscribers/<imsi>."""

    # Setup DRF permissions and auth.  This endpoint should only be accessed
    # via token auth, but for DRF to work properly you must also enable
    # session auth.
    permission_classes = (permissions.IsAuthenticated,)
    authentication_classes = (authentication.SessionAuthentication,
                              authentication.TokenAuthentication)

    def delete(self, request, imsi):
        network = get_network_from_user(request.user)
        subscriber = models.Subscriber.objects.get(imsi=imsi)
        if subscriber.network != network:
            return Response("Network is not associated with that Subscriber.",
                            status=status.HTTP_403_FORBIDDEN)
        # This is a valid request, begin processing.
        subscriber.deactivate()
        return Response("")


class Tower(APIView):
    """Handles /api/v2/towers/<uuid>."""

    # Setup DRF permissions and auth.  This endpoint should only be accessed
    # via token auth, but for DRF to work properly you must also enable
    # session auth.
    permission_classes = (permissions.IsAuthenticated,)
    authentication_classes = (authentication.SessionAuthentication,
                              authentication.TokenAuthentication)

    def delete(self, request, tower_uuid):
        network = get_network_from_user(request.user)
        tower = models.BTS.objects.get(uuid=tower_uuid)
        if tower.network and tower.network != network:
            return Response("Network is not associated with that BTS.",
                            status=status.HTTP_403_FORBIDDEN)
        # Create a DerigisteredBTS instance.
        dbts = models.DeregisteredBTS(uuid=tower.uuid, secret=tower.secret)
        dbts.save()
        # Create a 'deregister_bts' UsageEvent.
        now = datetime.datetime.now(pytz.utc)
        if tower.nickname:
            name = 'tower "%s" (%s)' % (tower.nickname, tower.uuid)
        else:
            name = 'tower %s' % tower.uuid
        event = models.UsageEvent.objects.create(
            date=now, bts_uuid=tower.uuid, kind='deregister_bts',
            reason='deregistered %s' % name)
        event.save()
        # TODO(matt): generate revocation certs
        # And finally delete the BTS.
        tower.delete()
        return Response("")

cloud/endagaweb/templates/dashboard/subscriber_detail/activity.html
{% extends "dashboard/layout.html" %}
{% comment %}
Copyright (c) 2016-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
{% endcomment %}
{% load apptags %}
{% load humanize %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}

{% block pagestyle %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.14.30/css/bootstrap-datetimepicker.min.css">
{% endblock %}


{% block title %} {% tmpl_const "SITENAME" %} | {{ subscriber.imsi }} Activity {% endblock %}


{% block content %}
{% include "dashboard/subscriber_detail/header.html" with subscriber=subscriber %}


<div class="row">
  {% include "dashboard/subscriber_detail/nav.html" with active_tab='activity' imsi=subscriber.imsi %}

  <div class="content col-xs-12 col-sm-7">

    {% if total_number_of_events %}
    <h4>Filter</h4>
    <form action="{% url 'subscriber-activity' imsi=subscriber.imsi %}"
          class="form-horizontal" method="post" role="form" onsubmit="setloading()">

      {% csrf_token %}

      <input type="hidden" id="id_subscriber" name="imsi"
             value="{{ subscriber.imsi }}">

      <div class="form-group">
        <label for="id_keyword" class="control-label col-xs-2">Keyword</label>
        <div class="col-xs-10">
          <input class="form-control" id="id_keyword" name="keyword" type="text"
                 value="{{ keyword|default_if_none:"" }}"/>
        </div>
      </div>

      <div class="form-group">
        <label for="id_start_date" class="control-label col-xs-2">From</label>
        <div class="col-xs-4">
          <input class="form-control" id="start_date" name="start_date"
                 type="text"
                 {% if start_date %}
                 value="{{ start_date }}"
                 {% endif %}
          />
        </div>

        <label for="id_end_date" class="control-label col-xs-2">Until</label>
        <div class="col-xs-4">
          <input class="form-control" id="end_date" name="end_date" type="text"
                 {% if end_date %}
                 value="{{ end_date }}"
                 {% endif %}
          />
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-xs-2">Services</label>
        <div class="col-xs-5">
          {% for service in all_services %}
            <label class="checkbox-inline">
              <input type="checkbox" name="services[]"
                     value="{{ service | lower }}"
                     {% if service in checked_services %}checked{% endif %}>
                {{ service }}
              </input>
            </label>
          {% endfor %}
        </div>

        <div class="col-xs-5">
          <button id="submit" type="submit" name="submit" value="Filter"
                  class="btn btn-primary col-xs-12"
                  data-loading-text="Loading...">Filter</button>
        </div>
      </div>

    </form>
    {% else %}
    {% comment %} This else is the other half of 'if total_number_of_events.'
                  We will hide everything if there is no activity to show.
    {% endcomment %}
    <p>This subscriber has not made any calls or sent any SMS.</p>
    {% endif %}
  </div>
</div>


{% if total_number_of_events %}
<div class='row'>
  <div class='content col-xs-12 col-sm-offset-2 col-sm-10'>
    {% if number_of_filtered_events == 0 %}
      <h4>No events matched your search.</h4>
    {% else %}
      {% render_table subscriber_activity_table %}
      {% include 'dashboard/timezone-notice.html' %}
    {% endif %}
  </div>
</div>
{% endif %}


{% endblock %}


{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.14.30/js/bootstrap-datetimepicker.min.js"></script>
<script src="/static/js/dashboard/activity.js"></script>
{% endblock %}

cloud/endagaweb/templates/dashboard/subscriber_detail/adjust_credit.html
{% extends "dashboard/layout.html" %}
{% comment %}
Copyright (c) 2016-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
{% endcomment %}
{% load apptags %}
{% load humanize %}
{% load crispy_forms_tags %}


{% block title %} {% tmpl_const "SITENAME" %} | {{ subscriber.imsi }} Send SMS {% endblock %}


{% block content %}
{% include "dashboard/subscriber_detail/header.html" with subscriber=subscriber %}

<div class='row'>
  {% include "dashboard/subscriber_detail/nav.html" with imsi=subscriber.imsi active_tab='adjust_credit'%}

  <div class='content col-xs-12 col-md-4'>
    <div class='row'>
      <div class='col-xs-12'>
        {% crispy credit_update_form %}
        <p class='col-xs-12'>Subscriber's current balance: {% currency subscriber.balance %}</p>
      </div>
      <div class='col-xs-12'>
        {% for message in messages %}
          <div class='alert alert-danger message'>{{ message }}</div>
        {% endfor %}
      </div>
    </div>
  </div>

  <div class='content col-xs-12 col-md-4'>
    {% if pending_updates %}
      <strong>Pending credit updates</strong>

      {% if subscriber.bts.status != 'active' %}
      <p>
        Warning: this subscriber is not currently on an active BTS,
        so credit updates will be delayed.
      </p>
      {% endif %}

      {% for p in pending_updates %}
      <p>
        {{ forloop.counter }}.
        {% if p.amount < 0 %} Deduct {% else %} Add {% endif %}
        {% currency p.abs_amount %}
        ({{ p.date | naturaltime}})
        <a class='pending-credit-update-cancel-button'
           onclick="deletePendingUpdate('{{ p.uuid }}')">cancel</a>
      </p>
      {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock %}


{% block js %}
<script>
  // Load the endpoint into the global context so that we can use it for
  // deleting PendingCreditUpdates in subscriber.js.
  var adjust_credit_url = "{% url 'subscriber-adjust-credit' imsi=subscriber.imsi %}";
</script>
<script src="/static/js/dashboard/subscriber.js"></script>
{% endblock %}

cloud/endagaweb/templates/dashboard/subscriber_detail/header.html
{% comment %}
Copyright (c) 2016-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
{% endcomment %}
<div class="row col-xs-12 page-header">
  <h3>
    {% if subscriber.name %}
      {{ subscriber.name }}
      <small>
        {{ subscriber.imsi }}
      </small>
    {% else %}
      {{ subscriber.imsi }}
    {% endif %}
  </h3>
</div>

cloud/endagaweb/templates/dashboard/subscriber_detail/info.html
{% extends "dashboard/layout.html" %}
{% comment %}
Copyright (c) 2016-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
{% endcomment %}
{% load apptags %}
{% load humanize %}
{% load crispy_forms_tags %}


{% block title %} {% tmpl_const "SITENAME" %} | {{ subscriber.imsi }} Info {% endblock %}


{% block content %}
{% include "dashboard/subscriber_detail/header.html" with subscriber=subscriber %}

<div class = 'row'>
  {% include "dashboard/subscriber_detail/nav.html" with imsi=subscriber.imsi active_tab='info'%}

  <div class='content col-xs-12 col-sm-10'>
      <p>
        <strong>Status</strong>:
        {% if subscriber.is_camped %}
          <span class='label label-success'>camped</span>
        {% elif subscriber.network.get_lowest_tower_version < "00000.00003.00021" %}
          <span class='label label-default'>unknown</span>
        {% else %}
          <span class='label label-default'>not camped</span>
        {% endif %}
      </p>
      <p>
        <strong>Number{{ subscriber.numbers_as_list|pluralize }}</strong>:
        {% if subscriber.numbers %}
          {{ subscriber.numbers }}
        {% else %}
          <i>none</i>
        {% endif %}
      </p>
      <p><strong>Balance</strong>: {% currency subscriber.balance %}</p>
      {% if subscriber.bts.network.get_lowest_tower_version >= "00000.00003.00021" %}
        <p>
          <strong>Last Camped</strong>:
          {{ subscriber.last_camped | naturaltime }} on
          <a href="/dashboard/towers/{{ subscriber.bts.uuid }}">
            {% if subscriber.bts.nickname %}
              {{ subscriber.bts.nickname }} ({{ subscriber.bts.uuid|slice:"5" }}..)
            {% else %}
              {{ subscriber.bts.uuid|slice:"5" }}
            {% endif %}
          </a>
        </p>
      {% endif %}
      <p><strong>Last Active</strong>: {{ subscriber.last_active | naturaltime }}</p>
      <p><strong>Last Outbound Activity</strong>: {{ subscriber.last_outbound_activity | naturaltime }}</p>
      <p><strong>Registered</strong>: {{ created.date }} ({{ created | naturaltime }})</p>
      <p>
        <strong>Activity</strong>:
        <ul>
          <li>{{ num_sms }} SMS sent</li>
          <li>{{ number_of_calls }} calls ({{ voice_sec | duration }} total)</li>
          <li>{{ up_bytes }} of data uploaded</li>
          <li>{{ down_bytes }} of data downloaded</li>
          <li>{{ total_bytes }} of data total</li>
        </ul>
      </p>
  </div>
</div>
{% endblock %}